GET http://localhost:3001/api/persons/
###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons/3
###
GET http://localhost:3001/api/persons/401



### 

DELETE http://localhost:3001/api/persons/604a6613bb3bf519d534
###
DELETE http://localhost:3001/api/persons/101



###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "juan",
    "number": "12-43-234345"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "12-43-234345"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "12-43-234345"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "pepe",
    "number": "12-43-234345"
}

###

PUT http://localhost:3001/api/persons/604a6613bb3bf519d5341044
content-type: application/json

{
    "name": "dssdfsdf",
    "number": "nwe"
}
